apiVersion: 1

datasources:
  - name: ClickHouse
    uid: clickhouse
    type: grafana-clickhouse-datasource
    access: proxy
    jsonData:
      host: clickhouse
      port: 8123
      protocol: http
      username: analytics
      defaultDatabase: movie_analytics
    secureJsonData:
      password: analytics
    editable: false
