services:
  user-db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - user-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 2s
      timeout: 3s
      retries: 20

  users-auth:
    build: 
      context: ./services/users_auth
    ports:
      - "8000:8000"
    depends_on:
      user-db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@user-db:5432/postgres

volumes:
  user-db-data: