{
  "type": "record",
  "name": "WarehouseEvent",
  "namespace": "smart.warehouse",
  "fields": [
    {"name": "event_id", "type": "string"},
    {"name": "event_type", "type": "string"},
    {"name": "event_timestamp", "type": "string"},
    {"name": "product_id", "type": ["null", "string"], "default": null},
    {"name": "quantity", "type": ["null", "int"], "default": null},
    {"name": "counted_quantity", "type": ["null", "int"], "default": null},
    {"name": "zone_id", "type": ["null", "string"], "default": null},
    {"name": "from_zone_id", "type": ["null", "string"], "default": null},
    {"name": "to_zone_id", "type": ["null", "string"], "default": null},
    {"name": "order_id", "type": ["null", "string"], "default": null},
    {
      "name": "order_lines",
      "type": {
        "type": "array",
        "items": {
          "type": "record",
          "name": "OrderLine",
          "fields": [
            {"name": "product_id", "type": "string"},
            {"name": "zone_id", "type": "string"},
            {"name": "quantity", "type": "int"}
          ]
        }
      },
      "default": []
    },
    {"name": "entity_version", "type": ["null", "long"], "default": null}
  ]
}
