global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - /etc/prometheus/alerts.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: producer-service
    metrics_path: /metrics
    static_configs:
      - targets:
          - producer-service:8000

  - job_name: aggregation-service
    metrics_path: /metrics
    static_configs:
      - targets:
          - aggregation-service:8001

  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: postgres-exporter
    static_configs:
      - targets:
          - postgres-exporter:9187

  - job_name: kafka-exporter
    static_configs:
      - targets:
          - kafka-exporter:9308
